### ISSUE TITLE
Run rpk command to create ballast file

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#412] opened 2023-03-28 23:52 UTC
### What would you like to be added?

This issue is to track the need to verify ballast file creation works as expected. The docs say two things must happen:
1. proper config in values.yaml
2. run `rpk redpanda tune ballast_file`

See docs here: https://docs.redpanda.com/docs/manage/cluster-maintenance/disk-utilization/#create-a-ballast-file

In the chart I see step 1 but not step 2.

### Why is this needed?

This will allow configuring a ballast file properly.

JIRA Link: [K8S-33](https://redpandadata.atlassian.net/browse/K8S-33)

[K8S-33]: https://redpandadata.atlassian.net/browse/K8S-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alejandroEsc** [comment] 2023-03-30 14:53
I was able to get the ballast file to create BUT it is because I ran the tune process in the container where redpanda is running. To be clear, we need to distinguish and most probably run these commands in the right context. Those that require elevated privs should probably run in a daemonset, which imho we should create for customers as an option, and second we should run those that do not require elevelated privs (those that modify redpanda configs directly) should probably run in the postStart hook. @vuldin let me know what do you think of this approach?

**Comment by chrisseto** [comment] 2024-08-16 15:17
Duplicate of https://github.com/redpanda-data/helm-charts/issues/233

**Closed by chrisseto** 2024-08-16 15:17 UTC
Labels: investigation, P3
