### ISSUE TITLE
skipChown by default

### ISSUE THREAD

**Issue by patrickangeles** [redpanda-data/helm-charts#371] opened 2023-03-02 17:59 UTC
### What happened?

In the helm charts, there is a step to chown `/var/lib/redpanda/data` to the redpanda user. This requires privileged access which adds complexity for locked down environments. It also appears to be not necessary, though some research needs to happen to track down why the code made it in...

### What did you expect to happen?

Default install of helm charts should not attempt to chown

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```

</details>

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by hcoyote** [comment] 2023-03-02 19:24
This is basically a duplicate of #370.

**Closed** 2023-03-09 16:30 UTC
Labels: P0, chart:redpanda
