### ISSUE TITLE
redpanda: add rpk.additional_start_flags to values

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#281] opened 2023-01-18 20:07 UTC
There are occasions where extra command line arguments might be needed by rpk when starting redpanda. Add a value and use that value in the configmap template to add `additional_start_flags` to the `rpk` key.

**Comment by alejandroEsc** [comment] 2023-06-23 19:06
duplicate of https://github.com/redpanda-data/helm-charts/issues/394

**Closed by alejandroEsc** 2023-06-23 19:06 UTC
Labels: P3, chart:redpanda
