### ISSUE TITLE
Allow setting `--unsafe-bypass-fsync`

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#369] opened 2023-03-02 13:51 UTC
### What would you like to be added?

This would allow setting this redpanda value in development (non-production) environments.

### Why is this needed?

Some users want to use this mode while testing and not using slower (not expensive) disks to get better performance.

**Comment by joejulian** [comment] 2023-05-22 22:36
This is a duplicate of #445

**Closed by joejulian** 2023-05-22 22:36 UTC
Labels: enhancement, P2
