### ISSUE TITLE
Log a warning if Redpanda does not have exclusive access to cores

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#1247] opened 2024-04-24 10:55 UTC
### What would you like to be added?

Automated checks to see if Redpanda is running in a Pod with a `Guaranteed` QoS class and if the container has a CPU set assigned, logging a warning if either is false.

For example:

1. Confirm that the container is running with the `Guaranteed` QoS class.
    ```bash
    kubectl --namespace=<namespace> get pod <pod-name> -o jsonpath='{ .status.qosClass}{"\n"}'
    ```
2. Check that a cpuset has been assigned, indicating dedicated CPU resources.
    ```bash
    if [ ! -f /sys/fs/cgroup/cpuset/cpuset.cpus ]; then
    fi
    ```

If the check finds that the container does not meet these conditions, it should emit a warning log like "WARNING: Redpanda does not have exclusive access to CPU resources. This configuration may lead to suboptimal performance. For more information on enabling exclusive CPU access, see docs-link."

### Why is this needed?

Identifying whether a Redpanda container has exclusive access to cores can be cumbersome. This enhancement would benefit users by providing immediate feedback on their deployment's state without manual checks.

JIRA Link: [K8S-178](https://redpandadata.atlassian.net/browse/K8S-178)

[K8S-178]: https://redpandadata.atlassian.net/browse/K8S-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alejandroEsc** [comment] 2024-05-01 15:33
Where should this warning exist exactly? I think it makes sense to me that redpanda-operator would do this at the pod level as a condition. That would give a visual idea of the state of a particular broker. However, im not sure where a warning should be written, on the redpanda object as a status entry? Maybe as a post-upgrade/install hook?

**Comment by chrisseto** [comment] 2024-07-23 18:08
Closing this as "won't do" as I don't think the issue is valid anymore given all our learnings from Travis Downs 😓

**Closed by chrisseto** 2024-07-23 18:08 UTC
