### ISSUE TITLE
Helm upgrade --dry-run fails

### ISSUE THREAD

**Issue by ligfx** [redpanda-data/helm-charts#1277] opened 2024-05-13 14:40 UTC
### What happened?

```
Error: UPGRADE FAILED: template: redpanda/templates/statefulset.yaml:46:21:
executing "redpanda/templates/statefulset.yaml" at <include "statefulset-pod-labels-selector" .>:
error calling include: template: redpanda/templates/_statefulset.tpl:24:10:
executing "statefulset-pod-labels-selector" at <include "redpanda.StatefulSetPodLabelsSelector" (dict "a" (list . $sts))>: 
error calling include: template: redpanda/templates/_statefulset.go.tpl:23:78: 
executing "redpanda.StatefulSetPodLabelsSelector" at <$existing.spec.selector.matchLabels>:
nil pointer evaluating interface {}.selector
```

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

~~Originally thought the issues was with commonLabels:
helm install redpanda -n redpanda redpanda/redpanda --version 5.8.5 --set commonLabels.env=this-is-broken --create-namespace
helm upgrade redpanda -n redpanda redpanda/redpanda --version 5.8.5 --set commonLabels.env=this-is-broken~~

```sh
helm install redpanda -n redpanda redpanda/redpanda --version 5.8.5 --create-namespace
helm upgrade redpanda -n redpanda redpanda/redpanda --version 5.8.5 --dry-run
```

### Which are the affected charts?

Redpanda

### Chart Version(s)

```console
$ helm -n <redpanda-release-namespace> list 
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART         	APP VERSION
redpanda	redpanda	1       	2024-05-13 07:38:11.405376 -0700 PDT	deployed	redpanda-5.8.5	v24.1.1    

$ helm version
version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.22.2"}
```

### Cloud provider

Known to happen locally on k3d and in cloud against GKE

## Work Around

use `--dry-run=server` or `HELM_DIFF_USE_INSECURE_SERVER_SIDE_DRY_RUN=true` when using the helm-diff plugin.

**Comment by chrisseto** [comment] 2024-05-13 19:18
Pinned down the issue. Helm's lookup function returns an empty dictionary if the object isn't found instead of `nil` which is what's causing the null pointer issue.

I've got a mostly working but very involved fix that just needs some tests locally. I'll toss up a patch to work around the issue for now though.

**Comment by chrisseto** [comment] 2024-05-13 19:24
Huh... Actually I need to look deeper into this. The issue should only occur if there's _not_ redpanda STS in the cluster. Any given upgrade should find such a STS...

**Comment by chrisseto** [comment] 2024-05-13 19:44
@ligfx I actually can't reproduce this on either kind or k3d. The upgrade completes with no issues.

```
❯ k3d version
k3d version v5.6.0
k3s version v1.21.7-k3s1 (default)
❯ helm version
version.BuildInfo{Version:"v3.14.4", GitCommit:"v3.14.4", GitTreeState:"", GoVersion:"go1.22.2"}
❯ kind version
kind v0.22.0 go1.22.2 darwin/arm64
```

Did you take any steps between running the install and the upgrade? Did you wait for the all pods in the cluster to become ready before initiating the upgrade?

I can trigger the same error message as you're seeing but only if I delete the STS in between the install and upgrade. Which isn't really an expected use case 😓 
```
Error: UPGRADE FAILED: template: redpanda/templates/statefulset.yaml:46:21: executing "redpanda/templates/statefulset.yaml" at <include "statefulset-pod-labels-selector" .>: error calling include: template: redpanda/templates/_statefulset.tpl:24:10: executing "statefulset-pod-labels-selector" at <include "redpanda.StatefulSetPodLabelsSelector" (dict "a" (list . $sts))>: error calling include: template: redpanda/templates/_statefulset.go.tpl:23:78: executing "redpanda.StatefulSetPodLabelsSelector" at <$existing.spec.selector.matchLabels>: nil pointer evaluating interface {}.selector
```

**Comment by ligfx** [comment] 2024-05-13 20:27
Huh. I missed an argument in the repro steps that didn't seem relevant, but it is: `--dry-run`

```
helm install redpanda -n redpanda redpanda/redpanda --version 5.8.5 --set commonLabels.env=this-is-broken --create-namespace
helm upgrade redpanda -n redpanda redpanda/redpanda --version 5.8.5 --set commonLabels.env=this-is-broken **--dry-run**
```

The actual upgrade works, but dry-run fails.

**Comment by chrisseto** [comment] 2024-05-13 21:22
AH. Yeah that'll do it. In that case I don't think I consider this issue to be as pressing as running without `--dry-run` will work as expected (Unless you delete the STS). I'll fix this as I initially intended to in that case.

**Comment by ligfx** [comment] 2024-05-14 13:38
> In that case I don't think I consider this issue to be as pressing

Agreed. I'm recommending people use `--dry-run=server` (or `HELM_DIFF_USE_INSECURE_SERVER_SIDE_DRY_RUN=true` when using the helm-diff plugin) for now if they want to do a dry run.

**Comment by diegs** [comment] 2024-05-20 19:42
I'm hitting this without using `--dry-run` afaict. We're using [rancher fleet](https://fleet.rancher.io/) to manage helm deployments. A simple no-op helm upgrade puts the release in a bad state:

```
template: redpanda/templates/statefulset.yaml:46:21: 
executing \"redpanda/templates/statefulset.yaml\" at <include \"statefulset-pod-labels-selector\" .>: 
error calling include: template: redpanda/templates/_statefulset.tpl:24:10: 
executing \"statefulset-pod-labels-selector\" at <include \"redpanda.StatefulSetPodLabelsSelector\" (dict \"a\" (list . $sts))>: 
error calling include: template: redpanda/templates/_statefulset.go.tpl:23:78: 
executing \"redpanda.StatefulSetPodLabelsSelector\" at <$existing.spec.selector.matchLabels>: nil pointer evaluating interface {}.selector
```

I know this isn't vanilla helm, and I'm struggling to find more information from the embedded helm controller, but I don't experience this with other charts and it seems related to the issue described above.

Are there any other workarounds I can use to unblock my helm pipeline? We're using the latest helm release (5.8.5). Thank you.

**Comment by chrisseto** [comment] 2024-05-21 14:09
We don't have any known work arounds right now but I can resurrect some of the work on this. It _should_ just need a bit of polishing.

I am curious about how you're hitting this case. Is this coming from a fresh install of the chart or an upgrade thereof? If the latter, is there a redpanda statefulset in your cluster?

**Comment by diegs** [comment] 2024-05-21 18:16
@chrisseto thanks the reply.

The fresh install of the chart worked fine. The [statefulset was created](https://github.com/redpanda-data/helm-charts/files/15393884/statefulset.yaml.txt) (file extension changed to txt to make github happy). Then when either updating some values or doing a "force sync" with Fleet (which I believe is doing a straightforward `helm upgrade` under the hood but I am still investigating), I hit the above issue. It could be that fleet is using helm in a similar manner to `--dry-run`?

The only thing that seems maybe off about the statefulset is the `volumeClaimTemplates` saying `status.phase: Pending`. From what I can tell looking at the cluster objects, the claims are bound and the pods are running happily.

**Comment by chrisseto** [comment] 2024-05-22 15:19
> The only thing that seems maybe off about the statefulset is the volumeClaimTemplates saying status.phase: Pending. From what I can tell looking at the cluster objects, the claims are bound and the pods are running happily.

I wouldn't worry about that. `status` gets set to all manor of strange things due to weird combinations of Go's marshaling and Kubernetes choices. IIRC recent  (Or maybe all) versions of Kubernetes will just ignore `status` unless the subresource is explicitly written to.

>  It could be that fleet is using helm in a similar manner to --dry-run?

That would be my guess? It may do a dry run just for safety purposes which unfortunately triggers this case. We should be able to get a fix released within the next two weeks. I'm curious about why it hits this case but that won't affect the actual fix, assuming my understanding of the issue is correct.

**Closed** 2024-05-23 09:34 UTC
Labels: bug
